apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: podinfo
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.sso }}
  sso:
    - name: SSO
      clientId: uds-core-podinfo
      redirectUris:
        - "https://podinfo.{{ .Values.domain }}/users/auth/openid_connect/callback"
  {{- end }}
  network:
    expose:
      - service: podinfo
        podLabels:
          app.kubernetes.io/name: podinfo
        host: podinfo
        gateway: tenant
        port: 9898

    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace

      - direction: Ingress
        remoteNamespace: monitoring
        remotePodLabels:
          app: prometheus
        podLabels:
          app.kubernetes.io/name: podinfo
        port: 15021
        description: "Monitoring"

